override INCLUDES += -I./
override DEFINES  +=
override CFLAGS += $(INCLUDES) $(DEFINES)
BUILD_DIR   = ./build
DISTRIB_DIR = ./dist

all: $(DISTRIB_DIR)/libcontainers.a

$(BUILD_DIR)/lists.o:
$(BUILD_DIR)/strings.o:
